// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileTreeNode =
  | { type: "directory"; path: string; children: Array<FileTreeNode> }
  | { type: "file"; path: string };
